spring:

  datasource:
    url: jdbc:mysql://localhost:3306/egg_biblioteca?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

# Configura cómo se manejan las trazas de error en las respuestas del servidor. En este caso,
#  las trazas de la pila ("stacktrace") no se incluirán en las respuestas.
server:
  error:
    include-stacktrace: never